"""empty message

Revision ID: 30140461b814
Revises: 
Create Date: 2022-05-28 12:12:26.279264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30140461b814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail'),
    sa.UniqueConstraint('flag')
    )
    op.create_table('patients',
    sa.Column('patient_tag', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('item_discription', sa.String(length=80), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('serial', sa.String(length=80), nullable=False),
    sa.Column('date_manufactured', sa.String(length=80), nullable=False),
    sa.Column('cost', sa.String(length=80), nullable=False),
    sa.Column('purchase_date', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('patient_tag'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_table('info')
    # ### end Alembic commands ###
